// prisma/data.ts
// Every person, partnership, and parent-child group on the poster.

export type PersonInput = {
  code: string;
  firstName: string;
  lastName: string;
  generation: number;
  gender?: "M" | "F";
  nicknames?: string;
  suffix?: string;
  occupation?: string;
  bio?: string;
  education?: string;
  birthDate?: string;
  deathDate?: string;
};

const p = (
  code: string,
  firstName: string,
  lastName: string,
  generation: number,
  details: Omit<PersonInput, "code" | "firstName" | "lastName" | "generation"> = {},
): PersonInput => ({ code, firstName, lastName, generation, ...details });

// Transcribed from the eight-page clan document dated 2024-12-10 and re-audited
// page by page against the scanned images (footnote numbers restart per family).
// Unknown names stay blank instead of being guessed. deathDate "Deceased" mirrors
// the "+" marker in the source.
export const people = [
  // Founding Cayabyab lineage
  p("C.0.1", "Roberto", "Gundayao", 0, { gender: "M" }),
  p("C.0.2", "Anacleta", "Junio", 0, { gender: "F" }),
  p("C.1", "Florentina", "Gundayao", 1, { gender: "F", nicknames: "Florin" }),
  p("C.1.s", "Marcelino", "Cayabyab", 1, { gender: "M" }),
  p("C.2", "Genoveva", "Gundayao", 1, { gender: "F" }),
  p("C.3", "Leonila", "Gundayao", 1, { gender: "F" }),
  p("C.4", "Marcela", "Gundayao", 1, { gender: "F" }),
  p("C.5", "Mariano", "Gundayao", 1, { gender: "M" }),
  p("C.6", "Marcelino", "Gundayao", 1, { gender: "M" }),
  p("C.7", "Rufina", "Gundayao", 1, { gender: "F" }),
  p("C.8", "Placido", "Gundayao", 1, { gender: "M" }),
  p("C.9", "Victorina", "Gundayao", 1, { gender: "F" }),

  // Children of Florentina Gundayao and Marcelino Cayabyab
  p("1.1", "Pablo", "Cayabyab", 2, { gender: "M" }),
  p("1.1.s", "Camela", "de Vera", 2, { gender: "F", nicknames: "Itang" }),
  p("1.2", "Teresa", "Cayabyab", 2, { gender: "F", nicknames: "Sisang" }),
  p("1.2.s", "Gregorio", "Gundayao", 2, { gender: "M", nicknames: "Gorio", occupation: "Traveling salesman" }),
  p("1.3", "Pastora", "Cayabyab", 2, { gender: "F" }),
  p("1.4", "Emeterio", "Cayabyab", 2, {
    gender: "M",
    nicknames: "Iryong",
    occupation: "Contractor of grape pickers in Stockton, California",
  }),
  p("1.4.s", "Teresita", "de Venecia", 2, { gender: "F", nicknames: "Tessie" }),
  p("1.5", "Pedro", "Cayabyab", 2, {
    gender: "M",
    nicknames: "Pero,Pete",
    occupation: "Member of Emeterio's grape-picking team",
  }),
  p("1.5.s", "Aurora", "", 2, { gender: "F", nicknames: "Auring" }),
  p("1.6", "Teodorico", "Cayabyab", 2, {
    gender: "M",
    nicknames: "Ikoy",
    occupation: "Government employee in California",
  }),
  p("1.6.s", "Giselda", "", 2, { gender: "F" }),
  p("1.7", "Esperita", "Cayabyab", 2, { gender: "F", nicknames: "Itay" }),
  p("1.7.s", "Enrique", "Reyes", 2, { gender: "M", occupation: "Government employee in Pangasinan" }),
  p("1.8", "Crispino", "Cayabyab", 2, {
    gender: "M",
    nicknames: "Pinoy",
    occupation: "Collector of small-town lottery bets",
  }),
  p("1.8.s", "Esperita", "", 2, { gender: "F", nicknames: "Itay" }),

  // Cayabyab branches named in the scan
  p("1.1.1", "Angel", "Cayabyab", 3, { gender: "M", nicknames: "Gil" }),
  p("1.1.2", "Caridad", "Cayabyab", 3, { gender: "F", nicknames: "Caring" }),
  p("1.2.1", "Jesusa", "Gundayao", 3, { gender: "F", nicknames: "Susay" }),
  p("1.2.2", "Guillermo", "Gundayao", 3, { gender: "M", nicknames: "Imoy" }),
  p("1.2.3", "Carmen", "Gundayao", 3, { gender: "F", bio: "Recorded as unmarried" }),
  p("1.2.4", "Mariano", "Gundayao", 3, { gender: "M", nicknames: "Anong" }),
  p("1.2.5", "Anita", "Gundayao", 3, { gender: "F", nicknames: "Annette" }),
  p("1.2.6", "Quentin", "Gundayao", 3),
  p("1.2.7", "Ernesto", "Gundayao", 3, { gender: "M" }),
  p("1.4.1", "Andrew", "Cayabyab", 3, { gender: "M" }),
  p("1.5.1", "Cristopher", "Cayabyab", 3, { gender: "M", nicknames: "Cris" }),
  p("1.5.2", "Cecilia", "Cayabyab", 3, { gender: "F" }),
  p("1.5.3", "Ronald", "Cayabyab", 3, { gender: "M" }),
  p("1.6.1", "Orlando", "Cayabyab", 3, { gender: "M" }),
  p("1.6.2", "Yolanda", "Cayabyab", 3, { gender: "F" }),
  p("1.7.1", "Gabriel", "Reyes", 3, { gender: "M" }),
  p("1.7.1.s", "Monica", "Tolentinno", 3, { gender: "F" }),
  p("1.7.2", "Romeo", "Reyes", 3, { gender: "M", nicknames: "Romy", deathDate: "Deceased" }),
  p("1.7.2.s", "Leonisa", "Gutierrez", 3, { gender: "F" }),
  p("1.7.1.1", "Marvin", "Reyes", 4, { gender: "M" }),
  p("1.7.1.2", "Jonsel", "Reyes", 4),
  p("1.7.1.3", "Niño", "Reyes", 4, { gender: "M" }),
  p("1.7.1.4", "Mateo", "Reyes", 4, { gender: "M" }),
  p("1.8.1", "Adelina", "Cayabyab", 3, {
    gender: "F",
    nicknames: "Adeling",
    bio: "The detailed entry spells the first name Adelino.",
  }),
  p("1.8.1.s", "Alejo", "Santos", 3, { gender: "M" }),
  p("1.8.2", "Carlos", "Cayabyab", 3, { gender: "M", nicknames: "Caloy" }),
  p("1.8.2.s", "Vanessa", "", 3, { gender: "F" }),
  p("1.8.3", "Felipe", "Cayabyab", 3, { gender: "M", nicknames: "Ipoc", bio: "Twin of Jose Cayabyab" }),
  p("1.8.3.s", "Lita", "Meolan", 3, { gender: "F" }),
  p("1.8.4", "Jose", "Cayabyab", 3, { gender: "M", bio: "Twin of Felipe Cayabyab" }),
  p("1.8.4.s", "Elena", "dela Vega", 3, { gender: "F" }),
  p("1.8.5", "Evelyn", "Cayabyab", 3, { gender: "F" }),
  p("C.U.1", "Siti", "Cayabyab", 2, {
    gender: "M",
    bio: "Named in the scan, but placement in the Cayabyab lineage was not confirmed.",
  }),
  p("C.U.1.s", "Pacita", "Montemayor", 2, { gender: "F" }),
  p("C.U.1.1", "Susan", "Cayabyab", 3, { gender: "F" }),
  p("C.U.1.2", "Antonio", "Cayabyab", 3, { gender: "M" }),
  p("C.U.1.3", "Dolores", "Cayabyab", 3, { gender: "F" }),

  // Domingo Bautista and Pastora Cayabyab descendants
  p("1.3.1", "Perfecto", "Bautista", 3, {
    gender: "M",
    nicknames: "Peling",
    occupation: "Medical doctor; governor of Sultan Kudarat province for three years",
    deathDate: "1980s",
  }),
  p("1.3.1.s1", "Milagros", "de la Vega", 3, { gender: "F", nicknames: "Mila", occupation: "Hospital administrator" }),
  p("1.3.1.s2", "Sue", "", 3, { gender: "F" }),
  p("1.3.1.s3", "Adela", "", 3, { gender: "F" }),
  p("1.3.1.1", "Gwendolyn", "Bautista", 4, { gender: "F", nicknames: "Gingging" }),
  p("1.3.1.1.s", "Miguel", "Roxas", 4, { gender: "M", nicknames: "Mike" }),
  p("1.3.1.2", "Bartolome", "Bautista", 4, { gender: "M", nicknames: "Barry" }),
  p("1.3.1.2.s", "Cristina", "", 4, { gender: "F", nicknames: "Cristy" }),
  p("1.3.1.2.1", "Eureka", "Bautista", 5),
  p("1.3.1.2.2", "Eunice", "Bautista", 5, { gender: "F" }),
  p("1.3.1.2.3", "Ome", "Bautista", 5),
  p("1.3.1.2.4", "Ulysses", "Bautista", 5, { gender: "M" }),
  p("1.3.1.3", "Perfecto", "Bautista", 4, {
    gender: "M",
    nicknames: "Pele",
    suffix: "Jr.",
    occupation: "Medical doctor",
  }),

  p("1.3.2", "Petrocencia", "Bautista", 3, {
    gender: "F",
    nicknames: "Patring",
    occupation: "School teacher and principal",
    deathDate: "Deceased",
  }),
  p("1.3.2.s", "Perfecto", "Velasquez", 3, {
    gender: "M",
    nicknames: "Peping",
    suffix: "Jr.",
    occupation: "Provincial assessor",
    deathDate: "Deceased",
  }),
  p("1.3.2.1", "Filomena", "Velasquez", 4, {
    gender: "F",
    nicknames: "Mina",
    occupation: "Physical education teacher",
  }),
  p("1.3.2.1.s", "Cresencio", "Cruzada", 4, { gender: "M", nicknames: "Cris", occupation: "Music teacher" }),
  p("1.3.2.1.1", "Christopher Brian", "Cruzada", 5, {
    gender: "M",
    nicknames: "Brian",
    occupation: "Medical technologist",
    bio: "Family now in Lancaster, New Hampshire.",
  }),
  p("1.3.2.1.1.s", "Edal", "Biona", 5, { gender: "F", occupation: "Medical technologist" }),
  p("1.3.2.1.1.1", "Mary Christadel", "Cruzada", 6, { gender: "F", nicknames: "Adel" }),
  p("1.3.2.1.2", "Paul Michael", "Cruzada", 5, {
    gender: "M",
    nicknames: "Paul",
    occupation: "Nurse",
    bio: "Family now in Bismarck, North Dakota; settling in Seattle, Washington in 2025.",
  }),
  p("1.3.2.1.2.s", "Sharon Jayne", "Santiago", 5, { gender: "F", nicknames: "Sha", occupation: "Nurse" }),
  p("1.3.2.1.3", "John Kenneth", "Cruzada", 5, { gender: "M", nicknames: "Kenneth", occupation: "Nurse; businessman" }),
  p("1.3.2.1.3.s", "Maria Janine", "Rubite", 5, {
    gender: "F",
    nicknames: "Jaja",
    occupation: "Special education teacher; businesswoman",
  }),
  p("1.3.2.1.3.1", "Maria Macey", "Cruzada", 6, { gender: "F", nicknames: "Macey" }),
  p("1.3.2.2", "Perfecto", "Velasquez", 4, { gender: "M", nicknames: "Jun", suffix: "Jr.", occupation: "Businessman" }),
  p("1.3.2.2.s", "Donatela", "Duque", 4, { gender: "F", nicknames: "Donna", occupation: "Physician" }),
  p("1.3.2.2.1", "Ysabelle", "Velasquez", 5, { gender: "F" }),
  p("1.3.2.3", "Lillie", "Velasquez", 4, {
    gender: "F",
    occupation: "Government employee, Bureau of Internal Revenue",
    education: "MBA",
  }),
  p("1.3.2.3.s", "Bienvenido", "Cruz", 4, {
    gender: "M",
    nicknames: "Bien",
    occupation: "Geodetic engineer, Land Management Bureau",
    education: "MBA",
  }),
  p("1.3.2.3.1", "Haerly Kim", "Cruz", 5, { nicknames: "Kim", occupation: "Geodetic engineer, DENR-NCR" }),
  p("1.3.2.3.2", "Aaron Biel", "Cruz", 5, { gender: "M", nicknames: "Biel" }),
  p("1.3.2.4", "Jude", "Velasquez", 4, {
    gender: "M",
    nicknames: "Ju-ju",
    education: "BS Business Administration",
    bio: "Family now in Hayward, California.",
  }),
  p("1.3.2.4.s", "Estela", "Durana", 4, { gender: "F", nicknames: "Telay", education: "BS Business Administration" }),
  p("1.3.2.4.1", "Kristine Anne", "Velasquez", 5, { gender: "F", nicknames: "Tin", occupation: "Nursing assistant" }),
  p("1.3.2.5", "Fe", "Velasquez", 4, {
    gender: "F",
    occupation: "Businesswoman",
    education: "BS Business Administration",
  }),
  p("1.3.2.5.s", "Eliseo", "Quiambao", 4, { gender: "M", nicknames: "Jojo", suffix: "III", deathDate: "Deceased" }),
  p("1.3.2.5.1", "Lourdes", "Quiambao", 5, { gender: "F", nicknames: "Lulu", occupation: "Nurse; businesswoman" }),
  p("1.3.2.5.1.s", "Bryan", "Diongco", 5, {
    gender: "M",
    nicknames: "Bry",
    occupation: "Businessman",
    education: "BS Business Administration",
  }),
  p("1.3.2.5.1.1", "St. Khaylie Mhae", "Diongco", 6, { gender: "F", nicknames: "Khaylie" }),
  p("1.3.2.5.2", "Ellyson", "Quiambao", 5, {
    gender: "M",
    nicknames: "Son",
    occupation: "Information technologist; businessman",
  }),
  p("1.3.2.5.2.s", "Jazmine", "Felipe", 5, {
    gender: "F",
    nicknames: "Jaz",
    occupation: "Hotel and restaurant management; businesswoman",
  }),
  p("1.3.2.5.2.1", "Pio Jayson", "Quiambao", 6, { gender: "M", nicknames: "Pio" }),
  p("1.3.2.5.2.2", "Ellyza Vanellope", "Quiambao", 6, {
    gender: "F",
    nicknames: "Elly",
    birthDate: "2024-11",
    bio: "Expected in November 2024 when the document was written.",
  }),

  p("1.3.3", "Rosario", "Bautista", 3, { gender: "F", nicknames: "Chayong", occupation: "School teacher" }),
  p("1.3.3.s", "Gonzalo", "del Fierro", 3, {
    gender: "M",
    occupation: "Disbursing officer, Department of Education",
    deathDate: "Deceased",
  }),
  p("1.3.3.1", "Evelyn", "del Fierro", 4, {
    gender: "F",
    occupation: "Entrepreneur: orchard, piggery, and rice fields",
    deathDate: "Deceased",
  }),
  p("1.3.3.1.s", "Mariano", "Tamayo", 4, { gender: "M", nicknames: "Mar", occupation: "US Navy" }),
  p("1.3.3.1.1", "Arlene", "Tamayo", 5, { gender: "F" }),
  p("1.3.3.1.1.s", "Tomas", "Martinez", 5, { gender: "M" }),
  p("1.3.3.1.1.1", "Pia Angeli", "Martinez", 6, { gender: "F" }),
  p("1.3.3.1.1.2", "Kalani", "Martinez", 6),
  p("1.3.3.1.2", "Mabel", "Tamayo", 5, { gender: "F" }),
  p("1.3.3.1.2.s", "Jason", "Alfonso", 5, { gender: "M" }),
  p("1.3.3.1.2.1", "Marc Jae Liam", "Alfonso", 6, {
    gender: "M",
    bio: 'The source prints "Marc Jae Liam, Alfonso, Louise"; read here as one child with the family surname.',
  }),
  p("1.3.3.1.2.2", "Louise", "Alfonso", 6, { gender: "F" }),
  p("1.3.3.1.3", "Mar Angelo", "Tamayo", 5, { gender: "M" }),
  p("1.3.3.1.3.s", "Krizza", "Cha", 5, { gender: "F" }),
  p("1.3.3.1.3.1", "Krza Zeline", "Tamayo", 6, { gender: "F", nicknames: "Celine" }),
  p("1.3.3.1.4", "Mark", "Tamayo", 5, { gender: "M", nicknames: "Toto" }),
  p("1.3.3.1.4.s", "Rowena Maria", "Mangilit", 5, { gender: "F" }),
  p("1.3.3.1.5", "Mae", "Tamayo", 5, { gender: "F", occupation: "Disbursing officer, Department of Education" }),
  p("1.3.3.1.5.s", "Cyrus", "Parsario", 5, { gender: "M" }),
  p("1.3.3.1.5.1", "Avelyn", "Parsario", 6, { gender: "F" }),
  p("1.3.3.1.5.2", "Malachi", "Parsario", 6, { gender: "M" }),
  p("1.3.3.2", "Alice", "del Fierro", 4, { gender: "F" }),
  p("1.3.3.2.s", "Melchor", "Taroy", 4, { gender: "M", nicknames: "Boy", occupation: "US Navy" }),
  p("1.3.3.2.1", "Melissa", "Taroy", 5, { gender: "F" }),
  p("1.3.3.2.1.s", "Constante", "", 5, { gender: "M" }),
  p("1.3.3.2.1.1", "Paul Dwayne", "Taroy", 6, { gender: "M" }),
  p("1.3.3.2.1.2", "Joaquin", "Taroy", 6, { gender: "M" }),
  p("1.3.3.2.1.3", "Celine Azura Kate", "Taroy", 6, { gender: "F" }),
  p("1.3.3.2.2", "John Melvin", "Taroy", 5, { gender: "M" }),
  p("1.3.3.2.3", "Alyssa", "Taroy", 5, { gender: "F" }),
  p("1.3.3.2.3.s", "Jay", "", 5, { gender: "M" }),
  p("1.3.3.2.3.1", "Jovannah Allysiah Zoe", "Taroy", 6, { gender: "F" }),
  p("1.3.3.2.4", "Nathalie", "Taroy", 5, { gender: "F", bio: "Twin of Nathaniel Taroy" }),
  p("1.3.3.2.5", "Nathaniel", "Taroy", 5, { gender: "M", bio: "Twin of Nathalie Taroy" }),
  p("1.3.3.3", "Romeo", "del Fierro", 4, { gender: "M", nicknames: "Romy" }),
  p("1.3.3.3.s", "Armida", "Sison", 4, { gender: "F", nicknames: "Minda" }),
  p("1.3.3.3.1", "Fay", "del Fierro", 5, { gender: "F" }),
  p("1.3.3.3.2", "Paul", "del Fierro", 5, { gender: "M" }),
  p("1.3.3.3.3", "Philip", "del Fierro", 5, { gender: "M" }),
  p("1.3.3.4", "Gonzalo", "del Fierro", 4, { gender: "M", nicknames: "Jojo", suffix: "Jr." }),
  p("1.3.3.4.s", "Grace", "Baldric", 4, { gender: "F" }),
  p("1.3.3.4.1", "Eivind", "del Fierro", 5, {
    gender: "M",
    bio: "The detailed entry spells the first name Eivine. Newly married as of 2024.",
  }),
  p("1.3.3.4.1.s", "Pauline", "del Mundo", 5, { gender: "F" }),
  p("1.3.3.4.2", "Abigail", "del Fierro", 5, { gender: "F", bio: "Recorded as single" }),
  p("1.3.3.4.3", "Jessica", "del Fierro", 5, { gender: "F", bio: "Newly married as of 2024." }),
  p("1.3.3.4.3.s", "Marcus", "Berberabe", 5, { gender: "M", nicknames: "Mark" }),
  p("1.3.3.5", "Ross", "del Fierro", 4, { gender: "M", occupation: "Medical doctor" }),
  p("1.3.3.5.s", "Annie", "Puno", 4, { gender: "F", occupation: "Medical doctor" }),
  p("1.3.3.5.1", "Rossanna", "del Fierro", 5, { gender: "F" }),

  p("1.3.4", "Roberto", "Bautista", 3, {
    gender: "M",
    nicknames: "Bert",
    occupation: "Professor; United Nations officer",
    bio: "Nineteen years as a professor in the Philippines, nine years in Malaysia, and ten years as a United Nations officer. UP Los Baños honored him by naming a building after him.",
    deathDate: "Deceased",
  }),
  p("1.3.4.s", "Ofelia", "Karganilla", 3, {
    gender: "F",
    nicknames: "Ofie",
    occupation: "Retired professor in horticulture",
    bio: "Director of a UP Los Baños research center for six years; recipient of many awards. Coordinator of this genealogy.",
  }),
  p("1.3.4.1", "Laura Grace", "Bautista", 4, {
    gender: "F",
    occupation: "Senior manager for food safety, Kraft Heinz",
  }),
  p("1.3.4.1.s", "John", "Haas", 4, { gender: "M", occupation: "Medical technologist" }),
  p("1.3.4.2", "Roberto", "Bautista", 4, {
    gender: "M",
    nicknames: "Bobby",
    suffix: "Jr.",
    occupation: "Economist; entrepreneur",
    bio: "President of the local Rotary International chapter and of Toastmasters International; recipient of several awards.",
  }),
  p("1.3.4.2.s", "Winonah", "Ilagan", 4, {
    gender: "F",
    nicknames: "Chay",
    occupation: "Dentist",
    bio: "President of the Los Baños Dental Club.",
  }),
  p("1.3.4.3", "Marissa", "Bautista", 4, {
    gender: "F",
    nicknames: "Riza,Maris",
    occupation: "Food scientist; instructor",
    bio: "Died at age 29 from complications of lupus.",
    deathDate: "Deceased",
  }),
  p("1.3.4.3.s", "Jimmy", "Hung", 4, { gender: "M", occupation: "Businessman" }),
  p("1.3.4.4", "Belinda Lucille", "Bautista", 4, {
    gender: "F",
    nicknames: "Lida,Belle",
    occupation: "Administrative officer",
  }),
  p("1.3.4.4.s", "Mark", "Costales", 4, { gender: "M", occupation: "Agricultural entrepreneur" }),
  p("1.3.4.4.1", "Yohann Mikhael", "Costales", 5, { gender: "M", nicknames: "Yohann" }),
  p("1.3.4.4.2", "Danielle Maria", "Costales", 5, { gender: "F", nicknames: "Nini,Danielle" }),
  p("1.3.4.5", "Kerry Phil", "Bautista", 4, {
    gender: "M",
    nicknames: "Kerry",
    occupation: "Medical doctor",
    bio: "President of the Makiling Medical Society and of the Laguna Medical Society; recipient of several awards.",
  }),
  p("1.3.4.5.s", "Genevieve", "Siazon", 4, {
    gender: "F",
    nicknames: "Gen",
    occupation: "Medical doctor",
    bio: "The source gives Gen and Kerry the same footnote number; the next footnote, medical doctor, is read as hers.",
  }),
  p("1.3.4.5.1", "Keila Gwyneth", "Bautista", 5, { gender: "F", nicknames: "Keila" }),

  p("1.3.5", "Teofilo", "Bautista", 3, {
    gender: "M",
    nicknames: "Turing",
    occupation: "Mechanical engineer",
    deathDate: "Deceased",
  }),
  p("1.3.5.s", "Emma", "Bongabong", 3, { gender: "F" }),
  p("1.3.5.1", "Evangeline", "Bautista", 4, { gender: "F", nicknames: "Vangie", occupation: "Nurse" }),
  p("1.3.5.1.s", "John", "Diao", 4, { gender: "M", occupation: "Nurse" }),
  p("1.3.5.1.1", "Dexter", "Diao", 5, { gender: "M" }),
  p("1.3.5.2", "Perry", "Bautista", 4, { gender: "M" }),
  p("1.3.5.2.s", "Rose", "Gile", 4, { gender: "F" }),

  p("1.3.6", "Salvador", "Bautista", 3, { gender: "M", nicknames: "Ador,Buddy" }),
  p("1.3.6.s", "Yolanda", "Vaño", 3, { gender: "F", nicknames: "Yoly", occupation: "Nurse" }),
  p("1.3.6.1", "Aida", "Bautista", 4, { gender: "F" }),
  p("1.3.6.1.s", "Ronnie", "Barr", 4, { gender: "M" }),
  p("1.3.6.1.1", "Dean", "Barr", 5, { gender: "M" }),
  p("1.3.6.1.2", "Josh", "Barr", 5, { gender: "M" }),
  p("1.3.6.1.3", "Tal", "Barr", 5),
  p("1.3.6.2", "Giovanni", "Bautista", 4, { gender: "M" }),
  p("1.3.6.2.s", "Jaja", "", 4, { gender: "F" }),
  p("1.3.6.3", "Jonathan", "Bautista", 4, { gender: "M" }),
  p("1.3.6.3.s", "Tricia", "", 4, { gender: "F" }),
  p("1.3.6.3.1", "Noah", "Bautista", 5, { gender: "M", bio: "The other parent was not named in the scan." }),
  p("1.3.6.4", "Andrew", "Bautista", 4, { gender: "M" }),

  p("1.3.7", "Teodora", "Bautista", 3, { gender: "F", nicknames: "Doray" }),
  p("1.3.7.s", "Caruso", "Dequina", 3, { gender: "M" }),
  p("1.3.7.1", "Teodycar", "Dequina", 4, { gender: "F" }),
  p("1.3.7.1.s1", "Tito", "Carumba", 4, { gender: "M" }),
  p("1.3.7.1.s2", "Rodrigo", "Alhambra", 4, { gender: "M" }),
  p("1.3.7.1.s3", "Zeus", "Palmes", 4, { gender: "M", nicknames: "Ameng" }),
  p("1.3.7.1.1", "Albert", "Carumba", 5, { gender: "M" }),
  p("1.3.7.1.1.s", "Mayin", "Chantil", 5, { gender: "F" }),
  p("1.3.7.1.2", "", "Alhambra", 5, { bio: "Name left blank in the source." }),
  p("1.3.7.1.3", "Monica", "Alhambra", 5, { gender: "F" }),
  p("1.3.7.1.4", "Rodrigo", "Alhambra", 5, { gender: "M", suffix: "Jr." }),
  p("1.3.7.1.5", "Juan Miguel", "Palmes", 5, { gender: "M" }),
  p("1.3.7.1.6", "Brian James", "Palmes", 5, { gender: "M" }),
  p("1.3.7.2", "Teresita", "Dequina", 4, { gender: "F", nicknames: "Teng,Terry", occupation: "Nurse" }),
  p("1.3.7.2.s", "Manolo", "Cruz", 4, { gender: "M", nicknames: "Noli" }),
  p("1.3.7.2.1", "Michael", "Cruz", 5, { gender: "M" }),
  p("1.3.7.2.2", "Sean", "Cruz", 5, { gender: "M" }),
  p("1.3.7.2.2.s", "Caitlyn", "Battitus", 5, { gender: "F" }),
  p("1.3.7.2.2.1", "Katherine", "Cruz", 6, { gender: "F" }),
  p("1.3.7.2.3", "Kevin", "Cruz", 5, { gender: "M" }),

  // Bautista ancestry, joined to the Cayabyab lineage through Domingo and Pastora
  p("B.0.1", "Carlos", "Bautista", 0, { gender: "M" }),
  p("B.0.2", "Victorina", "Macaraeg", 0, { gender: "F" }),
  p("B.1", "Claudio", "Bautista", 1, { gender: "M" }),
  p("B.1.s", "Marcelina", "Bustarde", 1, { gender: "F" }),
  p("B.2", "Dominga", "Bautista", 1, { gender: "F" }),
  p("B.2.s", "Ariston", "Llamsen", 1, { gender: "M" }),
  p("B.3", "Mariano", "Bautista", 1, { gender: "M" }),
  p("B.1.1", "Pedro", "Bautista", 2, { gender: "M" }),
  p("B.1.1.s", "Carnay", "Caranto", 2, { gender: "F" }),
  p("B.1.1.1", "Adela", "Bautista", 3, { gender: "F" }),
  p("B.1.1.1.s", "Juanita", "Mercado", 3),
  p("B.1.1.2", "Purita", "Bautista", 3, { gender: "F" }),
  p("B.1.1.3", "Felipe", "Bautista", 3, { gender: "M" }),
  p("B.1.1.3.s", "Senny", "", 3),
  p("B.1.1.4", "Sitoy", "Bautista", 3),
  p("B.1.2", "Jose", "Bautista", 2, { gender: "M" }),
  p("B.1.2.s", "Edang", "", 2, { gender: "F" }),
  p("B.1.2.1", "Rebecca", "Bautista", 3, { gender: "F" }),
  p("B.1.2.1.s", "Emong", "", 3, { gender: "M" }),
  p("B.1.2.2", "Ineng", "Bautista", 3, { gender: "F" }),
  p("B.1.2.2.s", "Berting", "", 3, { gender: "M" }),
  p("B.1.2.3", "Itang", "Bautista", 3),
  p("B.1.2.4", "Naty", "Bautista", 3, { gender: "F" }),
  p("B.1.2.4.s", "Martin", "", 3, { gender: "M" }),
  p("B.1.2.5", "Ester", "Bautista", 3, { gender: "F" }),
  p("B.1.2.6", "Flor", "Bautista", 3, { gender: "F" }),
  p("B.1.2.6.s", "Mario", "", 3, { gender: "M" }),
  p("B.1.2.7", "Eking", "Bautista", 3),
  p("B.1.3", "Domingo", "Bautista", 2, { gender: "M" }),
  p("B.2.1", "Francisca", "Bautista", 2, { gender: "F" }),
  p("B.2.1.s", "", "Martinez", 2, { gender: "M" }),
  p("B.2.1.1", "Rebecca", "Martinez", 3, { gender: "F", deathDate: "Deceased" }),
  p("B.2.1.2", "Juan", "Martinez", 3, { gender: "M", deathDate: "Deceased" }),
  p("B.2.1.3", "Araceli", "Martinez", 3, {
    gender: "F",
    nicknames: "Lily",
    occupation: "Lawyer in San Carlos City, Pangasinan",
  }),
  p("B.2.2", "Bartolome", "Bautista", 2, { gender: "M" }),
  p("B.2.3", "Inocencio", "Bautista", 2, { gender: "M" }),
  p("B.2.4", "Auring", "Bautista", 2, { gender: "F" }),
  p("B.2.4.s", "", "Mamaraglo", 2, { gender: "M" }),
] satisfies PersonInput[];

export type PartnershipInput = [string, string, "married" | "livein" | "divorced"];

export const partnerships: PartnershipInput[] = [
  ["C.0.1", "C.0.2", "married"],
  ["C.1", "C.1.s", "married"],
  ["1.1", "1.1.s", "married"],
  ["1.2", "1.2.s", "married"],
  ["1.3", "B.1.3", "married"],
  ["1.4", "1.4.s", "married"],
  ["1.5", "1.5.s", "married"],
  ["1.6", "1.6.s", "married"],
  ["1.7", "1.7.s", "married"],
  ["1.8", "1.8.s", "married"],
  ["C.U.1", "C.U.1.s", "married"],
  ["1.7.1", "1.7.1.s", "married"],
  ["1.7.2", "1.7.2.s", "married"],
  ["1.8.1", "1.8.1.s", "married"],
  ["1.8.2", "1.8.2.s", "married"],
  ["1.8.3", "1.8.3.s", "married"],
  ["1.8.4", "1.8.4.s", "married"],
  ["1.3.1", "1.3.1.s1", "married"],
  ["1.3.1", "1.3.1.s2", "livein"],
  ["1.3.1", "1.3.1.s3", "livein"],
  ["1.3.1.1", "1.3.1.1.s", "married"],
  ["1.3.1.2", "1.3.1.2.s", "married"],
  ["1.3.2", "1.3.2.s", "married"],
  ["1.3.2.1", "1.3.2.1.s", "married"],
  ["1.3.2.1.1", "1.3.2.1.1.s", "married"],
  ["1.3.2.1.2", "1.3.2.1.2.s", "married"],
  ["1.3.2.1.3", "1.3.2.1.3.s", "married"],
  ["1.3.2.2", "1.3.2.2.s", "married"],
  ["1.3.2.3", "1.3.2.3.s", "married"],
  ["1.3.2.4", "1.3.2.4.s", "married"],
  ["1.3.2.5", "1.3.2.5.s", "married"],
  ["1.3.2.5.1", "1.3.2.5.1.s", "married"],
  ["1.3.2.5.2", "1.3.2.5.2.s", "married"],
  ["1.3.3", "1.3.3.s", "married"],
  ["1.3.3.1", "1.3.3.1.s", "married"],
  ["1.3.3.1.1", "1.3.3.1.1.s", "married"],
  ["1.3.3.1.2", "1.3.3.1.2.s", "married"],
  ["1.3.3.1.3", "1.3.3.1.3.s", "married"],
  ["1.3.3.1.4", "1.3.3.1.4.s", "married"],
  ["1.3.3.1.5", "1.3.3.1.5.s", "married"],
  ["1.3.3.2", "1.3.3.2.s", "married"],
  ["1.3.3.2.1", "1.3.3.2.1.s", "livein"],
  ["1.3.3.2.3", "1.3.3.2.3.s", "livein"],
  ["1.3.3.3", "1.3.3.3.s", "married"],
  ["1.3.3.4", "1.3.3.4.s", "married"],
  ["1.3.3.4.1", "1.3.3.4.1.s", "married"],
  ["1.3.3.4.3", "1.3.3.4.3.s", "married"],
  ["1.3.3.5", "1.3.3.5.s", "married"],
  ["1.3.4", "1.3.4.s", "married"],
  ["1.3.4.1", "1.3.4.1.s", "married"],
  ["1.3.4.2", "1.3.4.2.s", "married"],
  ["1.3.4.3", "1.3.4.3.s", "married"],
  ["1.3.4.4", "1.3.4.4.s", "married"],
  ["1.3.4.5", "1.3.4.5.s", "married"],
  ["1.3.5", "1.3.5.s", "married"],
  ["1.3.5.1", "1.3.5.1.s", "married"],
  ["1.3.5.2", "1.3.5.2.s", "married"],
  ["1.3.6", "1.3.6.s", "married"],
  ["1.3.6.1", "1.3.6.1.s", "married"],
  ["1.3.6.2", "1.3.6.2.s", "married"],
  ["1.3.6.3", "1.3.6.3.s", "married"],
  ["1.3.7", "1.3.7.s", "married"],
  ["1.3.7.1", "1.3.7.1.s1", "married"],
  ["1.3.7.1", "1.3.7.1.s2", "livein"],
  ["1.3.7.1", "1.3.7.1.s3", "livein"],
  ["1.3.7.1.1", "1.3.7.1.1.s", "married"],
  ["1.3.7.2", "1.3.7.2.s", "divorced"],
  ["1.3.7.2.2", "1.3.7.2.2.s", "married"],
  ["B.0.1", "B.0.2", "married"],
  ["B.1", "B.1.s", "married"],
  ["B.2", "B.2.s", "married"],
  ["B.1.1", "B.1.1.s", "married"],
  ["B.1.1.1", "B.1.1.1.s", "married"],
  ["B.1.1.3", "B.1.1.3.s", "married"],
  ["B.1.2", "B.1.2.s", "married"],
  ["B.1.2.1", "B.1.2.1.s", "married"],
  ["B.1.2.2", "B.1.2.2.s", "married"],
  ["B.1.2.4", "B.1.2.4.s", "married"],
  ["B.1.2.6", "B.1.2.6.s", "married"],
  ["B.2.1", "B.2.1.s", "married"],
  ["B.2.4", "B.2.4.s", "married"],
];

export type FamilyInput = [string[], string[]];

export const families: FamilyInput[] = [
  [
    ["C.0.1", "C.0.2"],
    ["C.1", "C.2", "C.3", "C.4", "C.5", "C.6", "C.7", "C.8", "C.9"],
  ],
  [
    ["C.1", "C.1.s"],
    ["1.1", "1.2", "1.3", "1.4", "1.5", "1.6", "1.7", "1.8"],
  ],
  [
    ["1.1", "1.1.s"],
    ["1.1.1", "1.1.2"],
  ],
  [
    ["1.2", "1.2.s"],
    ["1.2.1", "1.2.2", "1.2.3", "1.2.4", "1.2.5", "1.2.6", "1.2.7"],
  ],
  [["1.4", "1.4.s"], ["1.4.1"]],
  [
    ["1.5", "1.5.s"],
    ["1.5.1", "1.5.2", "1.5.3"],
  ],
  [
    ["1.6", "1.6.s"],
    ["1.6.1", "1.6.2"],
  ],
  [
    ["1.7", "1.7.s"],
    ["1.7.1", "1.7.2"],
  ],
  [
    ["1.7.1", "1.7.1.s"],
    ["1.7.1.1", "1.7.1.2", "1.7.1.3", "1.7.1.4"],
  ],
  [
    ["1.8", "1.8.s"],
    ["1.8.1", "1.8.2", "1.8.3", "1.8.4", "1.8.5"],
  ],
  [
    ["C.U.1", "C.U.1.s"],
    ["C.U.1.1", "C.U.1.2", "C.U.1.3"],
  ],
  [
    ["1.3", "B.1.3"],
    ["1.3.1", "1.3.2", "1.3.3", "1.3.4", "1.3.5", "1.3.6", "1.3.7"],
  ],
  [["1.3.1", "1.3.1.s1"], ["1.3.1.1"]],
  [["1.3.1", "1.3.1.s2"], ["1.3.1.2"]],
  [["1.3.1", "1.3.1.s3"], ["1.3.1.3"]],
  [
    ["1.3.1.2", "1.3.1.2.s"],
    ["1.3.1.2.1", "1.3.1.2.2", "1.3.1.2.3", "1.3.1.2.4"],
  ],
  [
    ["1.3.2", "1.3.2.s"],
    ["1.3.2.1", "1.3.2.2", "1.3.2.3", "1.3.2.4", "1.3.2.5"],
  ],
  [
    ["1.3.2.1", "1.3.2.1.s"],
    ["1.3.2.1.1", "1.3.2.1.2", "1.3.2.1.3"],
  ],
  [["1.3.2.1.1", "1.3.2.1.1.s"], ["1.3.2.1.1.1"]],
  [["1.3.2.1.3", "1.3.2.1.3.s"], ["1.3.2.1.3.1"]],
  [["1.3.2.2", "1.3.2.2.s"], ["1.3.2.2.1"]],
  [
    ["1.3.2.3", "1.3.2.3.s"],
    ["1.3.2.3.1", "1.3.2.3.2"],
  ],
  [["1.3.2.4", "1.3.2.4.s"], ["1.3.2.4.1"]],
  [
    ["1.3.2.5", "1.3.2.5.s"],
    ["1.3.2.5.1", "1.3.2.5.2"],
  ],
  [["1.3.2.5.1", "1.3.2.5.1.s"], ["1.3.2.5.1.1"]],
  [
    ["1.3.2.5.2", "1.3.2.5.2.s"],
    ["1.3.2.5.2.1", "1.3.2.5.2.2"],
  ],
  [
    ["1.3.3", "1.3.3.s"],
    ["1.3.3.1", "1.3.3.2", "1.3.3.3", "1.3.3.4", "1.3.3.5"],
  ],
  [
    ["1.3.3.1", "1.3.3.1.s"],
    ["1.3.3.1.1", "1.3.3.1.2", "1.3.3.1.3", "1.3.3.1.4", "1.3.3.1.5"],
  ],
  [
    ["1.3.3.1.1", "1.3.3.1.1.s"],
    ["1.3.3.1.1.1", "1.3.3.1.1.2"],
  ],
  [
    ["1.3.3.1.2", "1.3.3.1.2.s"],
    ["1.3.3.1.2.1", "1.3.3.1.2.2"],
  ],
  [["1.3.3.1.3", "1.3.3.1.3.s"], ["1.3.3.1.3.1"]],
  [
    ["1.3.3.1.5", "1.3.3.1.5.s"],
    ["1.3.3.1.5.1", "1.3.3.1.5.2"],
  ],
  [
    ["1.3.3.2", "1.3.3.2.s"],
    ["1.3.3.2.1", "1.3.3.2.2", "1.3.3.2.3", "1.3.3.2.4", "1.3.3.2.5"],
  ],
  [
    ["1.3.3.2.1", "1.3.3.2.1.s"],
    ["1.3.3.2.1.1", "1.3.3.2.1.2", "1.3.3.2.1.3"],
  ],
  [["1.3.3.2.3", "1.3.3.2.3.s"], ["1.3.3.2.3.1"]],
  [
    ["1.3.3.3", "1.3.3.3.s"],
    ["1.3.3.3.1", "1.3.3.3.2", "1.3.3.3.3"],
  ],
  [
    ["1.3.3.4", "1.3.3.4.s"],
    ["1.3.3.4.1", "1.3.3.4.2", "1.3.3.4.3"],
  ],
  [["1.3.3.5", "1.3.3.5.s"], ["1.3.3.5.1"]],
  [
    ["1.3.4", "1.3.4.s"],
    ["1.3.4.1", "1.3.4.2", "1.3.4.3", "1.3.4.4", "1.3.4.5"],
  ],
  [
    ["1.3.4.4", "1.3.4.4.s"],
    ["1.3.4.4.1", "1.3.4.4.2"],
  ],
  [["1.3.4.5", "1.3.4.5.s"], ["1.3.4.5.1"]],
  [
    ["1.3.5", "1.3.5.s"],
    ["1.3.5.1", "1.3.5.2"],
  ],
  [["1.3.5.1", "1.3.5.1.s"], ["1.3.5.1.1"]],
  [
    ["1.3.6", "1.3.6.s"],
    ["1.3.6.1", "1.3.6.2", "1.3.6.3", "1.3.6.4"],
  ],
  [
    ["1.3.6.1", "1.3.6.1.s"],
    ["1.3.6.1.1", "1.3.6.1.2", "1.3.6.1.3"],
  ],
  [["1.3.6.3"], ["1.3.6.3.1"]],
  [
    ["1.3.7", "1.3.7.s"],
    ["1.3.7.1", "1.3.7.2"],
  ],
  [["1.3.7.1", "1.3.7.1.s1"], ["1.3.7.1.1"]],
  [
    ["1.3.7.1", "1.3.7.1.s2"],
    ["1.3.7.1.2", "1.3.7.1.3", "1.3.7.1.4"],
  ],
  [
    ["1.3.7.1", "1.3.7.1.s3"],
    ["1.3.7.1.5", "1.3.7.1.6"],
  ],
  [
    ["1.3.7.2", "1.3.7.2.s"],
    ["1.3.7.2.1", "1.3.7.2.2", "1.3.7.2.3"],
  ],
  [["1.3.7.2.2", "1.3.7.2.2.s"], ["1.3.7.2.2.1"]],
  [
    ["B.0.1", "B.0.2"],
    ["B.1", "B.2", "B.3"],
  ],
  [
    ["B.1", "B.1.s"],
    ["B.1.1", "B.1.2", "B.1.3"],
  ],
  [
    ["B.1.1", "B.1.1.s"],
    ["B.1.1.1", "B.1.1.2", "B.1.1.3", "B.1.1.4"],
  ],
  [
    ["B.1.2", "B.1.2.s"],
    ["B.1.2.1", "B.1.2.2", "B.1.2.3", "B.1.2.4", "B.1.2.5", "B.1.2.6", "B.1.2.7"],
  ],
  [
    ["B.2", "B.2.s"],
    ["B.2.1", "B.2.2", "B.2.3", "B.2.4"],
  ],
  [
    ["B.2.1", "B.2.1.s"],
    ["B.2.1.1", "B.2.1.2", "B.2.1.3"],
  ],
];
